# Generated by Django 5.1.1 on 2024-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_categorymodel_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='BookPrice',
            field=models.IntegerField(default=None),
        ),
    ]
