# Generated by Django 5.1.1 on 2024-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_categorymodel_slug_alter_bookmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
